POST http://localhost:8080/api/comment
Content-Type: application/json

{
  "game": "lightsOff",
  "player": "kseniya",
  "comment": "nice game",
  "commentedOn": "2022-04-11T12:40:33"
}
###
POST http://localhost:8080/api/comment
Content-Type: application/json

{
  "game": "lightsOff",
  "player": "Nick",
  "comment": "cool",
  "commentedOn": "2022-04-08T13:48:12"
}
