POST http://localhost:8080/api/rating
Content-Type: application/json

{
  "game": "lightsOff",
  "player": "kseniya",
  "rating": 4,
  "ratedOn": "2022-04-11T12:40:33"
}
###
POST http://localhost:8080/api/rating
Content-Type: application/json

{
  "game": "lightsOff",
  "player": "Nick",
  "rating": 5,
  "ratedOn": "2022-04-08T13:48:12"
}
